spring.application.name=fatecads

# Configurações do banco de dados 
spring.datasource.url=jdbc:postgresql://localhost:5432/fatecads_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Atualiza o esquema do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra as consultas SQL no console
spring.jpa.properties.hibernate.show_sql=true

# não formatar as consultas SQL
spring.jpa.properties.hibernate.format_sql=false

# configuração da porta do servidor 
server.port=8081
